defaults: &defaults
  adapter: mysql2
  encoding: utf8
  database: REPLACEME_DATABASE
  host: REPLACEME_HOSTNAME
  port: REPLACEME_PORT
  pool: 5
  username: REPLACEME_USER
  password: REPLACEME_PASSWORD

production:
  <<: *defaults
test:
  <<: *defaults
staging:
  <<: *defaults
development:
  <<: *defaults
